<?php

namespace App;


use Illuminate\Database\Eloquent\Model;
use App\RiskProfile;

class RiskFormAssesment extends Model
{
    protected $connection = 'mysql';
    protected $table = 'risk_form';
    protected $guarded = array();
    protected $fillable = [
        'risk_profile_id',
        'ar_chest_pain',
        'ar_difficulty_breathing',
        'ar_loss_of_consciousness',
        'ar_slurred_speech',
        'ar_facial_asymmetry',
        'ar_weakness_numbness',
        'ar_disoriented',
        'ar_chest_retractions',
        'ar_seizure_convulsion',
        'ar_act_self_harm_suicide',
        'ar_agitated_behavior',
        'ar_eye_injury',
        'ar_severe_injuries',
        'ar_refer_physician_name',
        'ar_refer_reason',
        'ar_refer_facility',
        'pmh_hypertension',
        'pmh_heart_disease',
        'pmh_diabetes',
        'pmh_specify_diabetes',
        'pmh_cancer',
        'pmh_specify_cancer',
        'pmh_copd',
        'pmh_asthma',
        'pmh_allergies',
        'pmh_specify_allergies',
        'pmh_mn_and_s_disorder',
        'pmh_specify_mn_and_s_disorder',
        'pmh_vision_problems',
        'pmh_previous_surgical',
        'pmh_specify_previous_surgical',
        'pmh_thyroid_disorders',
        'pmh_kidney_disorders',
        'fmh_hypertension',
        'fmh_side_hypertension',
        'fmh_stroke',
        'fmh_side_stroke',
        'fmh_heart_disease',
        'fmh_side_heart_disease',
        'fmh_diabetes_mellitus',
        'fmh_side_diabetes_mellitus',
        'fmh_asthma',
        'fmh_side_asthma',
        'fmh_cancer',
        'fmh_side_cancer',
        'fmh_kidney_disease',
        'fmh_side_kidney_disease',
        'fmh_first_degree_relative',
        'fmh_side_coronary_disease',
        'fmh_having_tuberculosis_5_years',
        'fmh_side_tuberculosis',
        'fmh_mn_and_s_disorder',
        'fmh_side_m_and_s_disorder',
        'fmh_copd',
        'fmh_side_copd',
        'rf_tobacco_use',
        'rf_alcohol_intake',
        'rf_alcohol_binge_drinker',
        'rf_physical_activity',
        'rf_nutrition_dietary',
        'rf_weight',
        'rf_height',
        'rf_body_mass',
        'rf_waist_circumference',
        'rs_systolic_t1',
        'rs_diastolic_t1',
        'rs_systolic_t2',
        'rs_diastolic_t2',
        'rs_blood_sugar_fbs',
        'rs_blood_sugar_rbs',
        'rs_blood_sugar_date_taken',
        'rs_blood_sugar_symptoms',
        'rs_lipid_cholesterol',
        'rs_lipid_hdl',
        'rs_lipid_ldl',
        'rs_lipid_vldl',
        'rs_lipid_triglyceride',
        'rs_lipid_date_taken',
        'rs_urine_protein',
        'rs_urine_protein_date_taken',
        'rs_urine_ketones',
        'rs_urine_ketones_date_taken',
        'rs_chronic_respiratory_disease',
        'rs_if_yes_any_symptoms',
        'mngm_med_hypertension',
        'mngm_med_hypertension_specify',
        'mngm_med_diabetes',
        'mngm_med_diabetes_options',
        'mngm_med_diabetes_specify',
        'mngm_date_follow_up',
        'mngm_remarks'
    ];
    
    public function risk_profile_Id(){
        return $this->belongsTo(RiskProfile::class, "id");
    }
}
