<?php

use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

class RenameRiskFromColumns extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('risk_form_temp', function (Blueprint $table) {
            $table->increments('id');
            $table->string('risk_profile_id', 255)->nullable();
            $table->string('ar_chestpain', 8)->nullable();
            $table->string('ar_diffBreath', 8)->nullable();
            $table->string('ar_lossOfConsciousness', 8)->nullable();
            $table->string('ar_slurredSpeech', 8)->nullable();
            $table->string('ar_facialAsymmetry', 8)->nullable();
            $table->string('ar_weaknessNumbness', 8)->nullable();
            $table->string('ar_disoriented', 8)->nullable();
            $table->string('ar_chestRetraction', 8)->nullable();
            $table->string('ar_seizureConvulsion', 8)->nullable();
            $table->string('ar_actSelfHarmSuicide', 8)->nullable();
            $table->string('ar_agitatedBehavior', 8)->nullable();
            $table->string('ar_eyeInjury',8)->nullable();
            $table->string('ar_severeInjuries', 8)->nullable();
            $table->string('ar_refer_physicianName', 255)->nullable();
            $table->string('ar_refer_reason', 255)->nullable();
            $table->string('ar_refer_facility', 255)->nullable();
            $table->string('pmh_hypertension', 8)->nullable();
            $table->string('pmh_heartDisease', 8)->nullable();
            $table->string('pmh_diabetes', 8)->nullable();
            $table->string('pmh_specify_diabetes', 255)->nullable();
            $table->string('pmh_cancer', 8)->nullable();
            $table->string('pmh_specify_cancer', 255)->nullable();
            $table->string('pmh_copd', 8)->nullable();
            $table->string('pmh_asthma', 8)->nullable();
            $table->string('pmh_allergies', 8)->nullable();
            $table->string('pmh_specify_allergies', 255)->nullable();
            $table->string('pmh_MNandSDisorder', 8)->nullable();
            $table->string('pmh_specify_MNandSdDisorder', 255)->nullable();
            $table->string('pmh_visionProblems', 8)->nullable();
            $table->string('pmh_previous_Surgical', 8)->nullable();
            $table->string('pmh_specify_previous_Surgical', 255)->nullable();
            $table->string('pmh_thyroidDisorders', 8)->nullable();
            $table->string('pmh_kidneyDisorders', 8)->nullable();
            $table->string('fm_hypertension', 8)->nullable();
            $table->string('fm_sideHypertension', 255)->nullable();
            $table->string('fm_stroke', 255)->nullable();
            $table->string('fm_sideStroke', 255)->nullable();
            $table->string('fm_heartDisease', 255)->nullable();
            $table->string('fm_sideHeartDisease', 255)->nullable();
            $table->string('fm_diabetesMel', 255)->nullable();
            $table->string('fmh_sideDiabetesMellitus', 255)->nullable();
            $table->string('fmh_asthma', 255)->nullable();
            $table->string('fmh_sideAsthma', 255)->nullable();
            $table->string('fmh_cancer', 255)->nullable();
            $table->string('fmh_sideCancer', 255)->nullable();
            $table->string('fmh_kidneyDisease', 255)->nullable();
            $table->string('fmh_sideKidneyDisease', 255)->nullable();
            $table->string('fmh_firstdegreRelative', 255)->nullable();
            $table->string('fmh_sideCoronaryDisease', 255)->nullable();
            $table->string('fmh_havingTB5years', 255)->nullable();
            $table->string('fmh_sideTuberculosis', 255)->nullable();
            $table->string('fmh_MNandSDisorder', 255)->nullable();
            $table->string('fm_sideDisorders', 255)->nullable();
            $table->string('fmh_COPD', 255)->nullable();
            $table->string('fmh_sideCOPD', 255)->nullable();
            $table->string('rf_tobbacoUse', 255)->nullable();
            $table->string('rf_alcoholIntake', 255)->nullable();
            $table->string('rf_alcoholBingeDrinker', 255)->nullable();
            $table->string('rf_physicalActivity', 255)->nullable();
            $table->string('rf_nutritionDietary', 255)->nullable();
            $table->float('rf_weight', 8, 2)->nullable();
            $table->float('rf_height', 8, 2)->nullable();
            $table->float('rf_bodyMass', 8, 2)->nullable();
            $table->float('rf_waistCircum', 8, 2)->nullable();
            $table->float('rs_systolic_t1', 8, 2)->nullable();
            $table->float('rs_diastolic_t1', 8, 2)->nullable();
            $table->float('rs_systolic_t2', 8, 2)->nullable();
            $table->float('rs_diastolic_t2', 8, 2)->nullable();
            $table->float('rs_bloodSugar_fbs', 8, 2)->nullable();
            $table->float('rs_bloodSugar_rbs', 8, 2)->nullable();
            $table->date('rs_bloodSugar_date_taken')->nullable();
            $table->string('rs_bloodSugar_symptoms', 255)->nullable();
            $table->float('rs_lipid_cholesterol', 8, 2)->nullable();
            $table->float('rs_lipid_hdl', 8, 2)->nullable();
            $table->float('rs_lipid_ldl', 8, 2)->nullable();
            $table->float('rs_lipid_vldl', 8, 2)->nullable();
            $table->float('rs_lipid_triglyceride', 8, 2)->nullable();
            $table->date('rs_lipid_date_taken')->nullable();
            $table->float('rs_urine_protein', 8, 2)->nullable();
            $table->date('rs_urine_protein_date_taken')->nullable();
            $table->float('rs_urine_ketones', 8, 2)->nullable();
            $table->date('rs_urine_ketones_date_taken')->nullable();
            $table->string('rs_Chronic_Respiratory_Disease', 255)->nullable();
            $table->string('rs_if_yes_any_symptoms', 255)->nullable();
            $table->string('mngm_med_hypertension', 255)->nullable();
            $table->string('mngm_med_hypertension_specify', 255)->nullable();
            $table->string('mngm_med_diabetes', 255)->nullable();
            $table->string('mngm_med_diabetes_options', 255)->nullable();
            $table->string('mngm_med_diabetes_specify', 255)->nullable();
            $table->date('mngm_date_follow_up')->nullable();
            $table->text('mngm_remarks')->nullable();
            $table->timestamps();
        });

        db::statement('insert into risk_form_temp select * from risk_form');

        Schema::dropIfExists('risk_form');

        Schema::create('risk_form', function (Blueprint $table) {
            $table->increments('id');
            $table->string('risk_profile_id', 255)->nullable();
            $table->string('ar_chest_pain', 8)->nullable();
            $table->string('ar_difficulty_breathing', 8)->nullable();
            $table->string('ar_loss_of_consciousness', 8)->nullable();
            $table->string('ar_slurred_speech', 8)->nullable();
            $table->string('ar_facial_asymmetry', 8)->nullable();
            $table->string('ar_weakness_numbness', 8)->nullable();
            $table->string('ar_disoriented', 8)->nullable();
            $table->string('ar_chest_retractions', 8)->nullable();
            $table->string('ar_seizure_convulsion', 8)->nullable();
            $table->string('ar_act_self_harm_suicide', 8)->nullable();
            $table->string('ar_agitated_behavior', 8)->nullable();
            $table->string('ar_eye_injury',8)->nullable();
            $table->string('ar_severe_injuries', 8)->nullable();
            $table->string('ar_refer_physician_name', 255)->nullable();
            $table->string('ar_refer_reason', 255)->nullable();
            $table->string('ar_refer_facility', 255)->nullable();
            $table->string('pmh_hypertension', 8)->nullable();
            $table->string('pmh_heart_disease', 8)->nullable();
            $table->string('pmh_diabetes', 8)->nullable();
            $table->string('pmh_specify_diabetes', 255)->nullable();
            $table->string('pmh_cancer', 8)->nullable();
            $table->string('pmh_specify_cancer', 255)->nullable();
            $table->string('pmh_copd', 8)->nullable();
            $table->string('pmh_asthma', 8)->nullable();
            $table->string('pmh_allergies', 8)->nullable();
            $table->string('pmh_specify_allergies', 255)->nullable();
            $table->string('pmh_mn_and_s_disorder', 8)->nullable();
            $table->string('pmh_specify_mn_and_s_disorder', 255)->nullable();
            $table->string('pmh_vision_problems', 8)->nullable();
            $table->string('pmh_previous_surgical', 8)->nullable();
            $table->string('pmh_specify_previous_surgical', 255)->nullable();
            $table->string('pmh_thyroid_disorders', 8)->nullable();
            $table->string('pmh_kidney_disorders', 8)->nullable();
            $table->string('fmh_hypertension', 8)->nullable();
            $table->string('fmh_side_hypertension', 255)->nullable();
            $table->string('fmh_stroke', 255)->nullable();
            $table->string('fmh_side_stroke', 255)->nullable();
            $table->string('fmh_heart_disease', 255)->nullable();
            $table->string('fmh_side_heart_disease', 255)->nullable();
            $table->string('fmh_diabetes_mellitus', 255)->nullable();
            $table->string('fmh_side_diabetes_mellitus', 255)->nullable();
            $table->string('fmh_asthma', 255)->nullable();
            $table->string('fmh_side_asthma', 255)->nullable();
            $table->string('fmh_cancer', 255)->nullable();
            $table->string('fmh_side_cancer', 255)->nullable();
            $table->string('fmh_kidney_disease', 255)->nullable();
            $table->string('fmh_side_kidney_disease', 255)->nullable();
            $table->string('fmh_first_degree_relative', 255)->nullable();
            $table->string('fmh_side_coronary_disease', 255)->nullable();
            $table->string('fmh_having_tuberculosis_5_years', 255)->nullable();
            $table->string('fmh_side_tuberculosis', 255)->nullable();
            $table->string('fmh_mn_and_s_disorder', 255)->nullable();
            $table->string('fm_side_disorders', 255)->nullable();
            $table->string('fmh_copd', 255)->nullable();
            $table->string('fmh_side_copd', 255)->nullable();
            $table->string('rf_tobbaco_use', 255)->nullable();
            $table->string('rf_alcohol_intake', 255)->nullable();
            $table->string('rf_alcohol_binge_drinker', 255)->nullable();
            $table->string('rf_physical_activity', 255)->nullable();
            $table->string('rf_nutrition_dietary', 255)->nullable();
            $table->float('rf_weight', 8, 2)->nullable();
            $table->float('rf_height', 8, 2)->nullable();
            $table->float('rf_body_mass', 8, 2)->nullable();
            $table->float('rf_waist_circumference', 8, 2)->nullable();
            $table->float('rs_systolic_t1', 8, 2)->nullable();
            $table->float('rs_diastolic_t1', 8, 2)->nullable();
            $table->float('rs_systolic_t2', 8, 2)->nullable();
            $table->float('rs_diastolic_t2', 8, 2)->nullable();
            $table->float('rs_blood_sugar_fbs', 8, 2)->nullable();
            $table->float('rs_blood_sugar_rbs', 8, 2)->nullable();
            $table->date('rs_blood_sugar_date_taken')->nullable();
            $table->string('rs_blood_sugar_symptoms', 255)->nullable();
            $table->float('rs_lipid_cholesterol', 8, 2)->nullable();
            $table->float('rs_lipid_hdl', 8, 2)->nullable();
            $table->float('rs_lipid_ldl', 8, 2)->nullable();
            $table->float('rs_lipid_vldl', 8, 2)->nullable();
            $table->float('rs_lipid_triglyceride', 8, 2)->nullable();
            $table->date('rs_lipid_date_taken')->nullable();
            $table->float('rs_urine_protein', 8, 2)->nullable();
            $table->date('rs_urine_protein_date_taken')->nullable();
            $table->float('rs_urine_ketones', 8, 2)->nullable();
            $table->date('rs_urine_ketones_date_taken')->nullable();
            $table->string('rs_chronic_respiratory_disease', 255)->nullable();
            $table->string('rs_if_yes_any_symptoms', 255)->nullable();
            $table->string('mngm_med_hypertension', 8)->nullable();
            $table->string('mngm_med_hypertension_specify', 255)->nullable();
            $table->string('mngm_med_diabetes', 8)->nullable();
            $table->string('mngm_med_diabetes_options', 50)->nullable();
            $table->string('mngm_med_diabetes_specify', 255)->nullable();
            $table->date('mngm_date_follow_up')->nullable();
            $table->text('mngm_remarks')->nullable();
            $table->timestamps();
        });

        DB::statement('INSERT INTO risk_form SELECT * FROM risk_form_temp');

        Schema::dropIfExists('risk_form_temp');
    }

    public function down()
    {
        Schema::create('risk_form_temp', function (Blueprint $table) {
            $table->increments('id');
            $table->string('risk_profile_id', 255)->nullable();
            $table->string('ar_chest_pain', 8)->nullable();
            $table->string('ar_difficulty_breathing', 8)->nullable();
            $table->string('ar_loss_of_consciousness', 8)->nullable();
            $table->string('ar_slurred_speech', 8)->nullable();
            $table->string('ar_facial_asymmetry', 8)->nullable();
            $table->string('ar_weakness_numbness', 8)->nullable();
            $table->string('ar_disoriented', 8)->nullable();
            $table->string('ar_chest_retractions', 8)->nullable();
            $table->string('ar_seizure_convulsion', 8)->nullable();
            $table->string('ar_act_self_harm_suicide', 8)->nullable();
            $table->string('ar_agitated_behavior', 8)->nullable();
            $table->string('ar_eye_injury',8)->nullable();
            $table->string('ar_severe_injuries', 8)->nullable();
            $table->string('ar_refer_physician_name', 255)->nullable();
            $table->string('ar_refer_reason', 255)->nullable();
            $table->string('ar_refer_facility', 255)->nullable();
            $table->string('pmh_hypertension', 8)->nullable();
            $table->string('pmh_heart_disease', 8)->nullable();
            $table->string('pmh_diabetes', 8)->nullable();
            $table->string('pmh_specify_diabetes', 255)->nullable();
            $table->string('pmh_cancer', 8)->nullable();
            $table->string('pmh_specify_cancer', 255)->nullable();
            $table->string('pmh_copd', 8)->nullable();
            $table->string('pmh_asthma', 8)->nullable();
            $table->string('pmh_allergies', 8)->nullable();
            $table->string('pmh_specify_allergies', 255)->nullable();
            $table->string('pmh_mn_and_s_disorder', 8)->nullable();
            $table->string('pmh_specify_mn_and_s_disorder', 255)->nullable();
            $table->string('pmh_vision_problems', 8)->nullable();
            $table->string('pmh_previous_surgical', 8)->nullable();
            $table->string('pmh_specify_previous_surgical', 255)->nullable();
            $table->string('pmh_thyroid_disorders', 8)->nullable();
            $table->string('pmh_kidney_disorders', 8)->nullable();
            $table->string('fmh_hypertension', 8)->nullable();
            $table->string('fmh_side_hypertension', 255)->nullable();
            $table->string('fmh_stroke', 255)->nullable();
            $table->string('fmh_side_stroke', 255)->nullable();
            $table->string('fmh_heart_disease', 255)->nullable();
            $table->string('fmh_side_heart_disease', 255)->nullable();
            $table->string('fmh_diabetes_mellitus', 255)->nullable();
            $table->string('fmh_side_diabetes_mellitus', 255)->nullable();
            $table->string('fmh_asthma', 255)->nullable();
            $table->string('fmh_side_asthma', 255)->nullable();
            $table->string('fmh_cancer', 255)->nullable();
            $table->string('fmh_side_cancer', 255)->nullable();
            $table->string('fmh_kidney_disease', 255)->nullable();
            $table->string('fmh_side_kidney_disease', 255)->nullable();
            $table->string('fmh_first_degree_relative', 255)->nullable();
            $table->string('fmh_side_coronary_disease', 255)->nullable();
            $table->string('fmh_having_tuberculosis_5_years', 255)->nullable();
            $table->string('fmh_side_tuberculosis', 255)->nullable();
            $table->string('fmh_mn_and_s_disorder', 255)->nullable();
            $table->string('fm_side_disorders', 255)->nullable();
            $table->string('fmh_copd', 255)->nullable();
            $table->string('fmh_side_copd', 255)->nullable();
            $table->string('rf_tobbaco_use', 255)->nullable();
            $table->string('rf_alcohol_intake', 255)->nullable();
            $table->string('rf_alcohol_binge_drinker', 255)->nullable();
            $table->string('rf_physical_activity', 255)->nullable();
            $table->string('rf_nutrition_dietary', 255)->nullable();
            $table->float('rf_weight', 8, 2)->nullable();
            $table->float('rf_height', 8, 2)->nullable();
            $table->float('rf_body_mass', 8, 2)->nullable();
            $table->float('rf_waist_circumference', 8, 2)->nullable();
            $table->float('rs_systolic_t1', 8, 2)->nullable();
            $table->float('rs_diastolic_t1', 8, 2)->nullable();
            $table->float('rs_systolic_t2', 8, 2)->nullable();
            $table->float('rs_diastolic_t2', 8, 2)->nullable();
            $table->float('rs_blood_sugar_fbs', 8, 2)->nullable();
            $table->float('rs_blood_sugar_rbs', 8, 2)->nullable();
            $table->date('rs_blood_sugar_date_taken')->nullable();
            $table->string('rs_blood_sugar_symptoms', 255)->nullable();
            $table->float('rs_lipid_cholesterol', 8, 2)->nullable();
            $table->float('rs_lipid_hdl', 8, 2)->nullable();
            $table->float('rs_lipid_ldl', 8, 2)->nullable();
            $table->float('rs_lipid_vldl', 8, 2)->nullable();
            $table->float('rs_lipid_triglyceride', 8, 2)->nullable();
            $table->date('rs_lipid_date_taken')->nullable();
            $table->float('rs_urine_protein', 8, 2)->nullable();
            $table->date('rs_urine_protein_date_taken')->nullable();
            $table->float('rs_urine_ketones', 8, 2)->nullable();
            $table->date('rs_urine_ketones_date_taken')->nullable();
            $table->string('rs_chronic_respiratory_disease', 255)->nullable();
            $table->string('rs_if_yes_any_symptoms', 255)->nullable();
            $table->string('mngm_med_hypertension', 8)->nullable();
            $table->string('mngm_med_hypertension_specify', 255)->nullable();
            $table->string('mngm_med_diabetes', 8)->nullable();
            $table->string('mngm_med_diabetes_options', 50)->nullable();
            $table->string('mngm_med_diabetes_specify', 255)->nullable();
            $table->date('mngm_date_follow_up')->nullable();
            $table->text('mngm_remarks')->nullable();
            $table->timestamps();
        });

        db::statement('insert into risk_form_temp select * from risk_form');

        Schema::dropIfExists('risk_form');

        Schema::create('risk_form', function (Blueprint $table) {
            $table->increments('id');
            $table->string('risk_profile_id', 255)->nullable();
            $table->string('ar_chestpain', 8)->nullable();
            $table->string('ar_diffBreath', 8)->nullable();
            $table->string('ar_lossOfConsciousness', 8)->nullable();
            $table->string('ar_slurredSpeech', 8)->nullable();
            $table->string('ar_facialAsymmetry', 8)->nullable();
            $table->string('ar_weaknessNumbness', 8)->nullable();
            $table->string('ar_disoriented', 8)->nullable();
            $table->string('ar_chestRetraction', 8)->nullable();
            $table->string('ar_seizureConvulsion', 8)->nullable();
            $table->string('ar_actSelfHarmSuicide', 8)->nullable();
            $table->string('ar_agitatedBehavior', 8)->nullable();
            $table->string('ar_eyeInjury',8)->nullable();
            $table->string('ar_severeInjuries', 8)->nullable();
            $table->string('ar_refer_physicianName', 255)->nullable();
            $table->string('ar_refer_reason', 255)->nullable();
            $table->string('ar_refer_facility', 255)->nullable();
            $table->string('pmh_hypertension', 8)->nullable();
            $table->string('pmh_heartDisease', 8)->nullable();
            $table->string('pmh_diabetes', 8)->nullable();
            $table->string('pmh_specify_diabetes', 255)->nullable();
            $table->string('pmh_cancer', 8)->nullable();
            $table->string('pmh_specify_cancer', 255)->nullable();
            $table->string('pmh_copd', 8)->nullable();
            $table->string('pmh_asthma', 8)->nullable();
            $table->string('pmh_allergies', 8)->nullable();
            $table->string('pmh_specify_allergies', 255)->nullable();
            $table->string('pmh_MNandSDisorder', 8)->nullable();
            $table->string('pmh_specify_MNandSdDisorder', 255)->nullable();
            $table->string('pmh_visionProblems', 8)->nullable();
            $table->string('pmh_previous_Surgical', 8)->nullable();
            $table->string('pmh_specify_previous_Surgical', 255)->nullable();
            $table->string('pmh_thyroidDisorders', 8)->nullable();
            $table->string('pmh_kidneyDisorders', 8)->nullable();
            $table->string('fm_hypertension', 8)->nullable();
            $table->string('fm_sideHypertension', 255)->nullable();
            $table->string('fm_stroke', 255)->nullable();
            $table->string('fm_sideStroke', 255)->nullable();
            $table->string('fm_heartDisease', 255)->nullable();
            $table->string('fm_sideHeartDisease', 255)->nullable();
            $table->string('fm_diabetesMel', 255)->nullable();
            $table->string('fmh_sideDiabetesMellitus', 255)->nullable();
            $table->string('fmh_asthma', 255)->nullable();
            $table->string('fmh_sideAsthma', 255)->nullable();
            $table->string('fmh_cancer', 255)->nullable();
            $table->string('fmh_sideCancer', 255)->nullable();
            $table->string('fmh_kidneyDisease', 255)->nullable();
            $table->string('fmh_sideKidneyDisease', 255)->nullable();
            $table->string('fmh_firstdegreRelative', 255)->nullable();
            $table->string('fmh_sideCoronaryDisease', 255)->nullable();
            $table->string('fmh_havingTB5years', 255)->nullable();
            $table->string('fmh_sideTuberculosis', 255)->nullable();
            $table->string('fmh_MNandSDisorder', 255)->nullable();
            $table->string('fm_sideDisorders', 255)->nullable();
            $table->string('fmh_COPD', 255)->nullable();
            $table->string('fmh_sideCOPD', 255)->nullable();
            $table->string('rf_tobbacoUse', 255)->nullable();
            $table->string('rf_alcoholIntake', 255)->nullable();
            $table->string('rf_alcoholBingeDrinker', 255)->nullable();
            $table->string('rf_physicalActivity', 255)->nullable();
            $table->string('rf_nutritionDietary', 255)->nullable();
            $table->float('rf_weight', 8, 2)->nullable();
            $table->float('rf_height', 8, 2)->nullable();
            $table->float('rf_bodyMass', 8, 2)->nullable();
            $table->float('rf_waistCircum', 8, 2)->nullable();
            $table->float('rs_systolic_t1', 8, 2)->nullable();
            $table->float('rs_diastolic_t1', 8, 2)->nullable();
            $table->float('rs_systolic_t2', 8, 2)->nullable();
            $table->float('rs_diastolic_t2', 8, 2)->nullable();
            $table->float('rs_bloodSugar_fbs', 8, 2)->nullable();
            $table->float('rs_bloodSugar_rbs', 8, 2)->nullable();
            $table->date('rs_bloodSugar_date_taken')->nullable();
            $table->string('rs_bloodSugar_symptoms', 255)->nullable();
            $table->float('rs_lipid_cholesterol', 8, 2)->nullable();
            $table->float('rs_lipid_hdl', 8, 2)->nullable();
            $table->float('rs_lipid_ldl', 8, 2)->nullable();
            $table->float('rs_lipid_vldl', 8, 2)->nullable();
            $table->float('rs_lipid_triglyceride', 8, 2)->nullable();
            $table->date('rs_lipid_date_taken')->nullable();
            $table->float('rs_urine_protein', 8, 2)->nullable();
            $table->date('rs_urine_protein_date_taken')->nullable();
            $table->float('rs_urine_ketones', 8, 2)->nullable();
            $table->date('rs_urine_ketones_date_taken')->nullable();
            $table->string('rs_Chronic_Respiratory_Disease', 255)->nullable();
            $table->string('rs_if_yes_any_symptoms', 255)->nullable();
            $table->string('mngm_med_hypertension', 255)->nullable();
            $table->string('mngm_med_hypertension_specify', 255)->nullable();
            $table->string('mngm_med_diabetes', 255)->nullable();
            $table->string('mngm_med_diabetes_options', 255)->nullable();
            $table->string('mngm_med_diabetes_specify', 255)->nullable();
            $table->date('mngm_date_follow_up')->nullable();
            $table->text('mngm_remarks')->nullable();
            $table->timestamps();
        });

        DB::statement('INSERT INTO risk_form SELECT * FROM risk_form_temp');

        Schema::dropIfExists('risk_form_temp');
    }
}
